New blog posts
codeigniter4projects/website pull request #292
Opened 2022-06-10 05:23 UTC by lonnieezell

2022-06-10 06:42 UTC, kenjis commented on content/blog/2022-03-02.3.1.12-released.md
> +title: CodeIgniter 3.1.12 Released
CodeIgniter 3.1.13 ?

2022-06-10 06:48 UTC, kenjis commented on content/blog/2022-03-02.3.1.12-released.md
> +This includes a bug in the Session library that broke for PHP 5 due to a misnamed polyfill interface, and fixed a possible session fixation vulnerability where `session.use_strict_mode` wasn’t enforc
Isn't this sentence a little odd?

> This includes a bug in the Session library

Yes, and the bug was fixed in 3.1.13.

2022-06-10 11:12 UTC, MGatner requested changes
Please highlight that Shield is beta. 

Some general ideas (that don't necessarily apply to this PR, as the first of its kind)... I would like to see blog posts submitted by themselves without other content/style changes. Also we should think about moving these to a separate repo; this would have a few advantages:
1. Content updates wouldn't require new releases or pushes to `master`
2. We can identify a team of editors with access separate from the technical website team

Finally, if we want to pull in forum posts regularly we should consider an API to handle that.

2022-06-10 11:12 UTC, MGatner commented on content/blog/2022-06-02.shield.md
> +While this is an initial release, it already provides a fairly thorough set of features, that should handle the needs of 80% of the projects your work on. We hope you find it helpful, and we're looki
```suggestion
While this is a beta release, it already provides a fairly thorough set of features, that should handle the needs of 80% of the projects your work on. We hope you find it helpful, and we're looking forward to see it continue to help you build secure applications in the future.
```

2022-06-11 04:08 UTC, lonnieezell commented on content/blog/2022-03-02.3.1.12-released.md
> +title: CodeIgniter 3.1.12 Released
I guess they were both released that day. I'll stick with 3.1.13.

2022-06-11 04:15 UTC, lonnieezell commented on content/blog/2022-06-02.shield.md
> +While this is an initial release, it already provides a fairly thorough set of features, that should handle the needs of 80% of the projects your work on. We hope you find it helpful, and we're looki
> I would like to see blog posts submitted by themselves without other content/style changes. Also we should think about moving these to a separate repo; this would have a few advantages:

> Content updates wouldn't require new releases or pushes to master
> We can identify a team of editors with access separate from the technical website team

That's fair, we'd have to figure out the deploy process for that but should be relatively simple. I personally don't have an issue with content requiring a push to master, since the content is part of the site, but I'm fine either way. One of these days when we have more time (ha!) it would definitely be worth looking into. 

> Finally, if we want to pull in forum posts regularly we should consider an API to handle that.

Yeah, possibly. Might be tricky determining which posts to include, but I'm sure we could come up with some solution.

2022-06-11 07:29 UTC, Arhell approved these changes

2022-06-11 10:39 UTC, MGatner commented on content/blog/2022-06-02.shield.md
> +While this is an initial release, it already provides a fairly thorough set of features, that should handle the needs of 80% of the projects your work on. We hope you find it helpful, and we're looki
The API forums integration sounds like a fun project; I would be willing to take that on, time permitting, once we have a content repo. I'm thinking of a scraper for the announcements thread that opens a new PR with the Markdown-ified post content - that way we can just close and ignore ones we don't want and review, fix styling, change wording, etc, for ones we want to keep.

2022-06-11 10:41 UTC, MGatner approved these changes
Might need to rebase the style changes in.

2022-06-11 10:43 UTC, kenjis approved these changes

2022-06-13 03:49 UTC, merged