add new favicons
codeigniter4projects/website pull request #305
Opened 2022-07-31 22:30 UTC by Arhell

resolve https://github.com/codeigniter4projects/website/issues/303

2022-08-01 09:36 UTC, MGatner requested changes
The favicon sections are completely duplicated across the two layouts and should probably be extracted into their own view file. That doesn't need to be done in this PR, but please respond about SVG file format for line breaks.

2022-08-01 09:36 UTC, MGatner commented on public/favicons/favicon.svg
> +</style></svg>
Do the line breaks have to be awkward? Can the first line be split up more, or make all this into one line?

2022-08-02 09:59 UTC, Arhell commented on public/favicons/favicon.svg
> +</style></svg>
Done

2022-08-02 11:14 UTC, MGatner approved these changes
Looks good!

2022-08-03 21:42 UTC, merged