Add blog 4.3 release
codeigniter4projects/website pull request #354
Opened 2023-01-11 00:05 UTC by kenjis

2023-01-12 00:05 UTC, Arhell approved these changes

2023-01-12 10:56 UTC, MGatner requested changes

2023-01-12 10:56 UTC, MGatner commented on content/blog/2023-01-10.4.3-released.md
> +Thanks to the team and many contributors, we released v4.3.0 with many enhancements.
Since this is a blog I'm going to recommend more colloquial changes; doesn't mean anything is wrong, so take them or leave them. 
```suggestion
Thanks to the team and many contributors, we released v4.3.0 with lots of enhancements.
```

2023-01-12 10:56 UTC, MGatner commented on content/blog/2023-01-10.4.3-released.md
> +Please read [ChangeLog](https://www.codeigniter.com/user_guide/changelogs/v4.3.0.html) and [Upgrading Guide](https://www.codeigniter.com/user_guide/installation/upgrade_430.html) carefully.
```suggestion
Please read the [ChangeLog](https://www.codeigniter.com/user_guide/changelogs/v4.3.0.html) and the [Upgrading Guide](https://www.codeigniter.com/user_guide/installation/upgrade_430.html) carefully.
```

2023-01-12 10:56 UTC, MGatner commented on content/blog/2023-01-10.4.3-released.md
> +**You must update spark file and a few Config files.**
```suggestion
**You must update the spark executable and a few Config files.**
```

2023-01-12 10:56 UTC, MGatner commented on content/blog/2023-01-10.4.3-released.md
> +I hope most existing apps will not break unless you use your own classes that extend framework classes.
```suggestion
Most existing apps will not need more intervention, unless you use your own classes that extend framework classes.
```

2023-01-12 10:56 UTC, MGatner commented on content/blog/2023-01-10.4.3-released.md
> +- Database Forge supports to add indexes in the existing tables and name indexes
```suggestion
- Database Forge supports adding indexes in the existing tables and named indexes
```

2023-01-12 10:56 UTC, MGatner commented on content/blog/2023-01-10.4.3-released.md
> +You can see the list of enhancements in [ChangeLog](https://www.codeigniter.com/user_guide/changelogs/v4.3.0.html#enhancements)
```suggestion
You can see the list of enhancements in the [ChangeLog](https://www.codeigniter.com/user_guide/changelogs/v4.3.0.html#enhancements)
```

2023-01-12 12:57 UTC, MGatner approved these changes
Looks great! Thanks.

2023-01-13 00:37 UTC, merged

2023-01-13 00:39 UTC, kenjis commented
@MGatner Thank you for proofreading!
I appreciate it.